{{- if not (has .Values.redis.persistence.appendfsync (list "always" "everysec" "no")) }}
{{- fail "redis.persistence.appendfsync must be always, everysec, or no" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configuration
  labels:
    app: redis
data:
  master.conf: |
    maxmemory {{ .Values.redis.maxmemory }}
    maxmemory-policy noeviction
    maxclients 20000
    appendonly {{ ternary "yes" "no" .Values.redis.persistence.appendonly }}
    appendfsync {{ .Values.redis.persistence.appendfsync }}
    no-appendfsync-on-rewrite {{ ternary "yes" "no" .Values.redis.persistence.noAppendfsyncOnRewrite }}
    dbfilename dump.rdb
    dir /data
  slave.conf: |
    slaveof redis-ss-0.redis-ss.redis 6379
    maxmemory {{ .Values.redis.maxmemory }}
    maxmemory-policy noeviction
    maxclients 20000
    appendonly {{ ternary "yes" "no" .Values.redis.persistence.appendonly }}
    appendfsync {{ .Values.redis.persistence.appendfsync }}
    no-appendfsync-on-rewrite {{ ternary "yes" "no" .Values.redis.persistence.noAppendfsyncOnRewrite }}
    dir /data
