{{- if .Values.redis.podDisruptionBudget -}}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: redis
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
{{ toYaml .Values.redis.podDisruptionBudget | indent 2 }}
{{- end -}}
