[tool.commitizen]
name = "cz_conventional_commits"
version = "1.27.3"
tag_format = "syntho-cli-$version"
version_files = [
    "cli/pyproject.toml:version",
    "pyproject.toml:version",
    "dynamic-configuration/pyproject.toml:version"
]
