---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key

  # Run the Ruff formatter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff-format
        types_or: [python]
        exclude: ^helm|^docker-compose

  # Run the Helm linter.
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        types_or: [python]
        args: [--fix]
        exclude: ^helm|^docker-compose

  # Bandit security check
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args:
          - -c
          - pyproject.toml
        additional_dependencies:
          - bandit[toml]

  # shellchek, static analysis tool for shell scripts
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        # Optionally only show errors and warnings
        args: ["--severity=warning"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
