#!/bin/bash

## WARNING! THIS SCRIPT IS KEPT FOR BACKWARDS COMPATIBILITY PURPOSES

DEPLOYMENT_DIR="$DEPLOYMENT_DIR"
source $DEPLOYMENT_DIR/.env --source-only
VERSION="$VERSION"

source ${DEPLOYMENT_DIR}/.images.env --source-only
IMAGE_REGISTRY_SERVER="${IMAGE_REGISTRY_SERVER-syntho.azurecr.io}"
echo "IMAGE_REGISTRY_SERVER=$IMAGE_REGISTRY_SERVER" >> "$DEPLOYMENT_DIR/.pre.deployment.ops.env"

CHARTS_DIR=${DEPLOYMENT_DIR}/syntho-charts-${VERSION}/helm
echo "CHARTS_DIR=$CHARTS_DIR" >> "$DEPLOYMENT_DIR/.pre.deployment.ops.env"
