#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/utils.sh" --source-only

DEPLOYMENT_DIR="$DEPLOYMENT_DIR"
source $DEPLOYMENT_DIR/.env --source-only

LICENSE_KEY="$LICENSE_KEY"
REGISTRY_USER="$REGISTRY_USER"
REGISTRY_PWD="$REGISTRY_PWD"
ARCH="$ARCH"
KUBECONFIG="$KUBECONFIG"
VERSION="$VERSION"


source $DEPLOYMENT_DIR/.config.env --source-only

LICENSE_KEY="$LICENSE_KEY"
STORAGE_CLASS_NAME="$STORAGE_CLASS_NAME"
STORAGE_CLASS_ACCESS_MODE="$STORAGE_CLASS_ACCESS_MODE"
PV_LABEL_KEY="$PV_LABEL_KEY"
TLS_ENABLED="$TLS_ENABLED"
DOMAIN="$DOMAIN"
PROTOCOL="$PROTOCOL"
INGRESS_CONTROLLER="$INGRESS_CONTROLLER"


source $DEPLOYMENT_DIR/.resources.env --source-only

RAY_HEAD_CPU_REQUESTS="$RAY_HEAD_CPU_REQUESTS"
RAY_HEAD_CPU_LIMIT="$RAY_HEAD_CPU_LIMIT"
RAY_HEAD_MEMORY_REQUESTS="$RAY_HEAD_MEMORY_REQUESTS"
RAY_HEAD_MEMORY_LIMIT="$RAY_HEAD_MEMORY_LIMIT"


source $DEPLOYMENT_DIR/.images.env --source-only
if [[ "$ARCH" == "arm" ]]; then
    source "$DEPLOYMENT_DIR/.images-arm.env" --source-only
fi

RAY_OPERATOR_IMG_REPO="$RAY_OPERATOR_IMG_REPO"
RAY_OPEARATOR_IMG_TAG="$RAY_OPEARATOR_IMG_TAG"
RAY_IMAGE_IMG_REPO="$RAY_IMAGE_IMG_REPO"
RAY_IMAGE_IMG_TAG="$RAY_IMAGE_IMG_TAG"
SYNTHO_UI_CORE_IMG_REPO="$SYNTHO_UI_CORE_IMG_REPO"
SYNTHO_UI_CORE_IMG_VER="$SYNTHO_UI_CORE_IMG_VER"
SYNTHO_UI_BACKEND_IMG_REPO="$SYNTHO_UI_BACKEND_IMG_REPO"
SYNTHO_UI_BACKEND_IMG_VER="$SYNTHO_UI_BACKEND_IMG_VER"
SYNTHO_UI_FRONTEND_IMG_REPO="$SYNTHO_UI_FRONTEND_IMG_REPO"
SYNTHO_UI_FRONTEND_IMG_VER="$SYNTHO_UI_FRONTEND_IMG_VER"
