apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
    app: frontend
  name: frontend
spec:
  ports:
    - name: frontend-port
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: frontend
