name: Publish Python package to PyPI

on:
  push:
    tags:
     - '*'

jobs:
  build-n-publish:
    name: Build and publish Python package to PyPI
    permissions:
      id-token: write
    environment: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install pypa/setuptools
      run: >-
        python -m
        pip install wheel setuptools
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Update version in setup.py
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py
    - name: Build a binary wheel
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish package to PyPI
      uses:  pypa/gh-action-pypi-publish@release/v1
