{{- if .Values.core.podDisruptionBudget -}}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.core.name }}
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.core.name }}
{{ toYaml .Values.core.podDisruptionBudget | indent 2 }}
{{- end -}}
