
{{- if empty .Values.core.manualSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "core-secret"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  core.secret_key: {{ .Values.core.secret_key }}
  core.database_url: "postgresql+asyncpg://{{ .Values.core.db.username }}:{{ .Values.core.db.password }}@{{ .Values.core.db.host }}:{{ .Values.core.db.port | default "5432" }}/{{ .Values.core.db.name }}"
{{- end }}