apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.core.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
    app: {{ .Values.core.name }}
  name: {{ .Values.core.name }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.core.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.core.name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          env:
            - name: SERVICE_PORT
              value: {{quote .Values.core.port }}
            - name: SERVICE_WORKERS
              value: {{ quote .Values.core.workers }}
            - name: SERVICE_WORKER_TIMEOUT
              value: "{{ .Values.core.worker_timeout | default "3000" }}"
            - name: CORE_ADDRESS
              value: {{quote .Values.core.ray_address }}
            - name: REDIS_HOST
              value: {{ quote .Values.core.redis.host}}
            - name: REDIS_PORT
              value: {{ quote .Values.core.redis.port }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.core.manualSecretName | default "core-secret" }}
                  key: core.secret_key
            - name: DB_HOST
              value: {{ quote .Values.core.db.host}}
            - name: DB_PORT
              value: {{ quote .Values.core.db.port }}
            - name: DB_NAME
              value: {{ quote .Values.core.db.name }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.core.manualSecretName | default "core-secret" }}
                  key: core.db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.core.manualSecretName | default "core-secret" }}
                  key: core.db_password
            - name: LICENSE_KEY_SIGNED
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.core.manualSecretName | default "core-secret"}}
                  key: license_key
            # deprecated
            - name: APP_ENV
              value: {{ .Values.core.app_env | default "prod" }}
            - name: PORT
              value: {{quote .Values.core.port }}
            - name: MAX_WORKERS
              value: {{ quote .Values.core.workers }}
            - name: WORKER_TIMEOUT
              value: "{{ .Values.core.worker_timeout | default "3000" }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.core.manualSecretName | default "core-secret" }}
                  key: core.database_url
            - name: RAY_ADDRESS
              value: {{quote .Values.core.ray_address }}
            - name: CELERY_BROKER_URL
              value:  "redis://{{ .Values.core.redis.host}}:{{ .Values.core.redis.port }}/{{ .Values.core.redis.db }}"
            - name: CELERY_RESULT_BACKEND
              value:  "redis://{{ .Values.core.redis.host}}:{{ .Values.core.redis.port }}/{{ .Values.core.redis.db }}"
          {{- if or $.Values.core.env $.Values.core.envSecrets }}
            {{- range $key, $value := $.Values.core.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $secret := $.Values.core.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secret }}
                  key: {{ $key | quote }}
            {{- end }}
          {{- end }}
          name: {{ .Values.core.name }}
          volumeMounts:
            {{- toYaml .Values.core.volumeMounts | default "" | nindent 12 }}
          ports:
            - containerPort: {{ .Values.core.port }}
          imagePullPolicy: {{ .Values.core.imagePullPolicy | default "IfNotPresent"}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            limits:
              cpu: "1250m"
              ephemeral-storage: "3Gi"
              memory: "3Gi"
            requests:
              cpu: "500m"
              ephemeral-storage: "3Gi"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.core.port }}
            initialDelaySeconds: 50
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/status
              port: {{ .Values.core.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.core.volumes | default "" | nindent 8 }}
      restartPolicy: Always
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
status: {}
