{{- if empty .Values.manualSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: "ray-secret"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  license_key: {{ .Values.SynthoLicense }}
{{- end }}
