{{- if .Values.db.podDisruptionBudget -}}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: postgres
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: postgres
{{ toYaml .Values.db.podDisruptionBudget | indent 2 }}
{{- end }}
---
{{- if .Values.db.podDisruptionBudget -}}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: database
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: database
{{ toYaml .Values.db.podDisruptionBudget | indent 2 }}
{{- end -}}
