{{- if .Values.core.database_enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "syntho-core.labels" . | nindent 4 }}
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{quote .Values.core.db.name }}
            - name: POSTGRES_PASSWORD
              value: {{quote .Values.core.db.password }}
            - name: POSTGRES_USER
              value: {{quote .Values.core.db.username }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          name: postgres
          resources: {}
          imagePullPolicy: {{ .Values.db.image.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-data-1
              subPath: postgres
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always{{- include "syntho-core.labels" . | nindent 4 }}
      {{- if .Values.tolerations }}
      tolerations: {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- .Values.affinity | toYaml | nindent 8 }}
      {{- end }}
status: {}
{{- end }}
