# Default values for syntho-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

frontend_path:
frontend_url: syntho.company.com
frontend_protocol: http

SynthoLicense: "<put-your-own-license>"

core:
  replicaCount: 1
  image:
    repository: syntho.azurecr.io/syntho-core-api
    tag: latest
  name: core
  service:
    port: 8080
    type: ClusterIP
  volumes: []
  volumeMounts: []
  database_enabled: true
  celery_args: ['-A', 'app.celery', 'worker', '--loglevel=info', '--concurrency=4', '--max-memory-per-child=50000']
  db:
    username: postgres
    password: postgres
    name: rwdb
    host: postgres
    port: 5432
  port: 8080
  secret_key: ZzXj2az_fnnM59mviJc0hmU_jhcdIVaI51dbEkuiXLk=
  redis:
    host: redis-svc
    port: 6379
    db: 1
  ray_address: ray-cluster-head-svc
  workers: 1
  # Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  podDisruptionBudget: {}
  # If uncommented, disables the secret created by the Helm template, in order to change to a secret created differentlky
  # manualSecretName: core-secret

backend:
  replicaCount: 1
  image:
    repository: syntho.azurecr.io/syntho-core-backend
    tag: latest
  name: backend
  port: 8000
  workers: 1
  secret_key: ix!57KPgpcyu!&2mMn69pB#R8zLhxLXAexnNoF!XZvqHB9G4JG%QLmFnE8Rx^3bMF#EG7rAxnWK*7LzKWF8S62qbTC
  redis:
    host: redis-svc
    port: 6379
    db: 0
  service:
    port: 8000
  database_enabled: true
  db:
    user: syntho
    password: syntho-local-password
    name: syntho-backend
    host: database
    port: 5432
  user:
    username: admin
    password: password
    email: admin@company.com
  volumes: []
  volumeMounts: []
  # Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  podDisruptionBudget: {}
  env:
    SECURE_COOKIES: "true"
  # If uncommented, this disables the secret created by the Helm chart, and allows you to point to the values of your own secret
  # manualSecretName: backend-secret

frontend:
  replicaCount: 1
  name: frontend
  image:
    repository: syntho.azurecr.io/syntho-core-frontend
    tag: latest
  busyboxImage: busybox:1.28.0
  port: 3000
  service:
    port: 3000
  ingress:
    enabled: true
    name: frontend-ingress
    className: nginx
    annotations: {
      nginx.ingress.kubernetes.io/session-cookie-path: "/",
      nginx.ingress.kubernetes.io/use-regex: "true",
      nginx.ingress.kubernetes.io/proxy-buffer-size: "32k",
      nginx.ingress.kubernetes.io/affinity: "cookie",
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600",
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600",
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600",
      nginx.ingress.kubernetes.io/proxy-body-size: "512m",
    }
    hosts:
      - host: syntho.company.com
        paths:
          - path: /
            pathType: Prefix

    tls:
      conf:
        - hosts:
          - syntho.company.com
          secretName: frontend-tls
      enabled: false
  # Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  podDisruptionBudget: {}

db:
  image:
    repository: syntho.azurecr.io/postgres
    tag: 14-bookworm
  storageClassName: "default"
  pvLabelKey: ""
  # Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  podDisruptionBudget: {}

redis:
  replicaCount: 1
  image:
    repository: redis
    tag: 7.2-rc2
  storageClassName: "default"
  pvLabelKey: ""
  # Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  podDisruptionBudget: {}

imagePullSecrets:
  - name: syntho-cr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}

# Tolerations for nodes that have taints on them.
# Useful if you want to dedicate nodes to just run kafka-exporter
# https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# tolerations:
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## Pod scheduling preferences (by default keep pods within a release on separate nodes).
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## By default we don't set affinity
affinity: {}

# affinity:
#  podAffinity:
#    preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 50
#       podAffinityTerm:
#         labelSelector:
#           matchExpressions:
#           - key: app
#             operator: In
#             values:
#               - syntho
#         topologyKey: "kubernetes.io/hostname"
