name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          changelog_increment_filename: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Zip docker-compose and Helm charts
        run: |
          tar -czf docker-compose.tar.gz docker-compose
          tar -czf ray-helm-chart.tar.gz helm/ray
          tar -czf syntho-ui-helm-chart.tar.gz helm/syntho-ui
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "changelog.md"
          tag_name: ${{ env.REVISION }}
          files: |
            "changelog.md"
            "docker-compose.zip"
            "ray-helm-chart.zip"
            "syntho-ui-helm-chart.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
