name: Linting for Helm Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: 'helm/syntho-ui'
            dyff_args: '--exclude "frontend_url" --exclude "frontend_path" --exclude "frontend_protocol" --exclude "SynthoLicense" --exclude-regexp "core.image.*" --exclude-regexp "backend.image.*" --exclude-regexp "backend.user.*" --exclude-regexp "frontend.image.*" --exclude-regexp "redis.image.*" --exclude-regexp "db.image.*" --exclude "db.storageClassName" --exclude "db.pvLabelKey" --exclude "redis.storageClassName" --exclude "redis.pvLabelKey" --exclude "frontend.ingress.className" --exclude "frontend.ingress.hosts.0.host" --exclude "frontend.ingress.hosts.0.host" --exclude "frontend.ingress.tls.enabled" --exclude "frontend.ingress.tls.conf.0.hosts.0" --exclude "imagePullSecrets" --exclude "frontend.busyboxImage" --exclude-regexp "backend.env.*"'
          - dir: 'helm/ray/chart'
            dyff_args: '--exclude-regexp "ray-cluster.head.resources.*" --exclude-regexp "storage.*" --exclude-regexp "kuberay-operator.image.*" --exclude-regexp "kuberay-operator.imagePullSecrets.*" --exclude-regexp "ray-cluster.image.*" --exclude "SynthoLicense" --exclude "ray-cluster.head.initContainer.image" --exclude "ray-cluster.worker.initContainerImage"'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true

      - name: Install Dyff
        run: sudo apt install curl jq && curl --silent --location https://git.io/JYfAY | bash

      - name: Check differences between values.yaml and values.yaml.tpl
        run: dyff between ${{ matrix.dir }}/values.yaml ${{ matrix.dir }}/values.yaml.tpl ${{ matrix.dyff_args }} -s

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          dir=${{ matrix.dir }}
          if [[ $(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs helm) =~ $dir ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --chart-dirs helm --charts ${{ matrix.dir }} --validate-maintainers=false

  helm-ct-test:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          dir=helm/
          if [[ $(ct list-changed --target-branch ${{ github.event.repository.default_branch }} --chart-dirs helm) =~ $dir ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          version: v3.14.4

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (Ray)
        if: steps.list-changed.outputs.changed == 'true'
        run: helm template ray-cluster helm/ray/chart

      - name: Run chart-testing (Syntho)
        if: steps.list-changed.outputs.changed == 'true'
        run: helm install ray-cluster helm/syntho-ui --dry-run=server --debug
