name: Linting for Docker Compose

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./docker-compose
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check differences between .env and .env.tpl
        run: |
         export DIFF_LINES=$(
            ENV1=.env.tpl                                                                                                                                                                               ENV1=.env.tpl
            ENV2=example.env
            diff --suppress-common-lines -y \
              <(grep -v -E '^#|^$' ${ENV1} | cut -d= -f1 | sort) \
              <(grep -v -E '^#|^$' ${ENV2} | cut -d= -f1 | sort) | wc -l
          )
          echo "Number of differences: $DIFF_LINES"
          exit $DIFF_LINES
