IMAGE_REGISTRY_SERVER=syntho.azurecr.io
RAY_OPERATOR_IMG_REPO=syntho.azurecr.io/syntho-ray-operator
RAY_OPERATOR_IMG_TAG=latest
RAY_IMAGE_IMG_REPO=syntho.azurecr.io/syntho-ray
RAY_IMAGE_IMG_TAG={{ SYNTHO_STACK_VERSION }}-cpu
SYNTHO_UI_CORE_IMG_REPO=syntho.azurecr.io/syntho-core-api
SYNTHO_UI_CORE_IMG_TAG={{ SYNTHO_STACK_VERSION }}
SYNTHO_UI_BACKEND_IMG_REPO=syntho.azurecr.io/syntho-core-backend
SYNTHO_UI_BACKEND_IMG_TAG={{ SYNTHO_STACK_VERSION }}
SYNTHO_UI_FRONTEND_IMG_REPO=syntho.azurecr.io/syntho-core-frontend
SYNTHO_UI_FRONTEND_IMG_TAG={{ SYNTHO_STACK_VERSION }}
POSTGRES_IMG_REPO=syntho.azurecr.io/postgres
POSTGRES_IMG_TAG=latest
REDIS_IMG_REPO=redis
REDIS_IMG_TAG=7.2-rc2
